site_name: BERTopic
extra_css: [style.css]
repo_url: https://github.com/MaartenGr/BERTopic
site_url: https://maartengr.github.io/BERTopic/
site_description: Leveraging BERT and a class-based TF-IDF to create easily interpretable topics.
site_author: Maarten P. Grootendorst
use_directory_urls: false
nav:
  - Home: index.md
  - Guides:
      - Getting Started: tutorial/quickstart/quickstart.md
      - Custom Embeddings: tutorial/embeddings/embeddings.md
      - Topic Reduction: tutorial/topicreduction/topicreduction.md
      - Topic Representation: tutorial/topicrepresentation/topicrepresentation.md
      - Search Topics: tutorial/search/search.md
  - The Algorithm: tutorial/algorithm/algorithm.md
  - API:
      - BERTopic: api/bertopic.md
      - cTFIDF: api/ctfidf.md
  - Changelog: changelog.md
plugins:
  - mkdocstrings:
      setup_commands:
        - import bertopic
      watch:
        - bertopic
  - search
copyright: Copyright &copy; 2020 Maintained by <a href="https://github.com/MaartenGr">Maarten</a>.
theme:
  custom_dir: images/
  name: material
  icon:
    logo: material/library
  font:
    text: Ubuntu
    code: Ubuntu Mono
  favicon: icon.png
  logo: icon.png
  feature:
    tabs: true
  palette:
    primary: white
    accent: blue
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.highlight:
      use_pygments: true
  - toc:
      permalink: true
